# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 827c0eef8fa2bb558b94960844865759daa8f85ad76c8c915fb3629b3ce19862e721243e581799d2f4f78e791e9423050c5282a511af2240aff2adbf75e2b3b8

test:
  secret_key_base: c9a1ecf811a8062a68dc0907283ef754e6226f134d44332edcaaf4ef50fbc558157c9aeb5430187e764fa0498ac52edb1acb20ff3be4339390d16be17f70759e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
